OPENAI_API_KEY = "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"
ADZUNA_APP_ID  = "e0183de2"
ADZUNA_APP_KEY = "754c1282bce1414a138458bf39360371"